- name: Copies {{COMPONENT}} repo file
  ansible.builtin.copy:
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

# Installing mongodShell
- name: Installing {{COMPONENT}}
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: installed

- name: Enabling {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Starting {{COMPONENT}}
  ansible.builtin.systemd_service:
    state: started
    name: mongod
    enabled: yes 
    daemon_reload: yes

- name: Download and extract {{COMPONENT}} Schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: loading catalogue data
  ansible.builtin.shell: mongo --host mongodb-{{ENV}}.roboshop.internal < /tmp/mongodb-main/{{item}}.js
  loop:
      - catalogue
      - users

- name: Running uptime time 
  ansible.builtin.shell: set-hostname {{COMPONENT}}
