- name: Demo on Vars
  hosts: all
  vars:
    URL: play.google.com    #Play level variable, if you declare variable at play level all the tasks can inherit them.
  tasks: 
    - name: Printing URL
      ansible.builtin.debug:
        msg: "Value of URL is {{URL}}"    #in bash we use echo $VARNAME, in YAML {{VARNAME}}
    
    - name: Printing URL from task
      ansible.builtin.debug:
        msg: "Value of URL is {{URL}}" 
      vars:                           # Task level variables : if you declare a variable at task level,only that task can use
        URL: task.google.com


- name: Printing city name
  ansible.builtin.debug:
    msg: "{{CITY}}"  

- name: Printing OD Distro
      ansible.builtin.debug:
        msg: My OS Distro is {{ansible_distribution}} 

# Variable Precendece : cli variables > task variables > play variables

### When to use quotes and when not to use quotes in YAML while dealing with variables ?

###  ---> if in your print msg, if you just have varaible, then it's a must to enclose them in "" 's 