# Whenever ansible runs the playbook, it first collects the properties of all the machines and then it will start doing the CM -configuration management
# What is a FACT ?
# A fact nothing but the properties of the VM's. - virtual machine

# In ansible, if you attempt to print a variable that is not decalred, ANSIBLE throws an exception!
- name: Demo On Facts 
  hosts: all 
  vars:                          # Play level variables : if you declare a variable at play level, all tasks of the play can inherit them
    URL: play.google.com
  # gather_facts: false      

  tasks:
    - name: printing url
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      # in bash, we use "echo $URL"

    - name: printing url from task 
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}      
      vars:                              # Task level variables : if you declare a variable at task level,only that task can use
        URL: task.google.com

    # - name: Printing city name
    #   ansible.builtin.debug:
    #     msg: "{{CITY}}"     

    - name: Printing OD Distro
      ansible.builtin.debug:
        msg: My OS Distro is {{ansible_distribution}} 


