# In ansible, if any of the task in the play fails, the subsequent tasks will fail
### https://docs.ansible.com/ansible/2.8/user_guide/playbooks_error_handling.html

- name: Demo on errors
  hosts: all 
  tasks:
    - name: Check Tomcat Is Running or Not 
      ansible.builtin.shell: ps -ef | grep java | grep -v grep      
      register: OUT    
      ignore_errors: true

    - name: Run Shipping 
      ansible.builtin.debug:
        msg: "Shipping is up" 