### https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html   Doc to create USER


- name: Demo on conditions 
  hosts: all 
  tasks: 
    - name: Checking User
      ansible.builtin.shell: id
      register: OUT
    
    - name: Printing User details
      ansible.builtin.debug:
        msg: "Username is {{OUT.stdout}}"