- name: Configuring Roboshop Project
  become: true
  # hosts: "{{COMPONENT}}"
  hosts: frontend
  roles:
    # - role: "{{COMPONENT}}"                      # Name of the role to run 
    - role: frontend  

