- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present 

### https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html

#Download happens in the destination machine or server
- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes


- name: Performing {{COMPONENT}} cleanup
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent


- name: Copying {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copies {{COMPONENT}} proxy file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: yes
    daemon_reload: true

- name: Configuring Server Name 
  ansible.builtin.shell: set-hostname {{COMPONENT}}
