- name: Enabling NodeJS18
  ansible.builtin.shell: dnf module disable nodejs -y ;  dnf module enable nodejs:18 -y

- name: Installing NodeJS
  ansible.builtin.dnf:
    name: nodejs 
    state: installed 

- name: Creating {{APPUSER}} user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Dealing Artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Generating Artifacts
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Configuring Svc
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Set name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name